USE Commissions
GO

DROP TABLE AGENT
GO

DROP TABLE OFFICE
GO

DROP TABLE BOOKING
GO

CREATE TABLE AGENT (
AGENTID INT PRIMARY KEY NOT NULL,
FIRSTNAME VARCHAR(50) NOT NULL,
LASTNAME VARCHAR(50) NOT NULL, 
OFFICENAME VARCHAR(50) NOT NULL,
RATE NUMERIC(6,5) NOT NULL,
FTE NUMERIC(6,2) NOT NULL,
OTE MONEY NOT NULL
)
GO

CREATE TABLE OFFICE (
OFFICENAME VARCHAR(50),
OFFICETARGET MONEY NOT NULL,
SALESDATE DATE NOT NULL
)

GO

CREATE TABLE BOOKING (
BOOKINGID INT PRIMARY KEY NOT NULL,
AGENTID INT NOT NULL,
OFFICENAME VARCHAR(50) NOT NULL,
BOOKINGDATE DATE NOT NULL,
REVENUE MONEY NOT NULL
)
GO

select table_name from information_schema.tables
